# https://alacritty.org/config-alacritty.html

[mouse]
hide_when_typing = true

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"

[window]
decorations = "Buttonless"
opacity = 0.8
option_as_alt = "OnlyLeft" # "Both"

[window.padding]
x = 7
y = 0

[keyboard]
bindings = [
  # { mods = "Control", key = "F", action = "ToggleFullscreen" },
  # { mods = "Control", key = "N", action = "CreateNewWindow" },

  # In chars
  # YAML expects hex escape sequences
  # TOML expects Unicode escape sequences
  # Make CTRL + 6 work https://github.com/alacritty/alacritty/issues/8038#issuecomment-2346411632
  { mods = "Control", key = "Key6", chars = "\u001e" },
]

# themes from https://github.com/alacritty/alacritty-theme
# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
